[build]
  publish = "."
  command = ""

[build.environment]
  PHP_VERSION = "8.1"

# Handle PHP files
[[redirects]]
  from = "/*.php"
  to = "/:splat"
  status = 200

# Handle root and other routes
[[redirects]]
  from = "/"
  to = "/index.php"
  status = 200

[[redirects]]
  from = "/*"
  to = "/:splat.php"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
