[build]
  publish = "."
  command = "echo 'No build step required'"

# Serve static HTML
[[redirects]]
  from = "/"
  to = "/index-static.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
